// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALsi2hbdMzRwQ_JQ8XM5HTRkarg0C0gX0',
    appId: '1:916064056591:web:03a1ee77bd5769604dba7a',
    messagingSenderId: '916064056591',
    projectId: 'diploma-d9c10',
    authDomain: 'diploma-d9c10.firebaseapp.com',
    storageBucket: 'diploma-d9c10.appspot.com',
    measurementId: 'G-9PFQJ8PNKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Bo5AUSqAElYcZjwyz8byDrIIzY65zWc',
    appId: '1:916064056591:android:a5084cda5b544a944dba7a',
    messagingSenderId: '916064056591',
    projectId: 'diploma-d9c10',
    storageBucket: 'diploma-d9c10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5GuO7_Ht55R39cSIPlPYnnHgZLEhCvXA',
    appId: '1:916064056591:ios:4d04d3651e78801d4dba7a',
    messagingSenderId: '916064056591',
    projectId: 'diploma-d9c10',
    storageBucket: 'diploma-d9c10.appspot.com',
    iosBundleId: 'com.example.diplomaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5GuO7_Ht55R39cSIPlPYnnHgZLEhCvXA',
    appId: '1:916064056591:ios:fafdb811c22a7f874dba7a',
    messagingSenderId: '916064056591',
    projectId: 'diploma-d9c10',
    storageBucket: 'diploma-d9c10.appspot.com',
    iosBundleId: 'com.example.diplomaTask.RunnerTests',
  );
}
